
export enum Actions{GetLogsForCurrentUser, InsertLogForCurrentUser, GetTimerRunsForCurrentUser, InsertTimerRunForCurrentUser, DeleteLogElementForCurrentUser, DeleteTimerRunForCurrentUser, GetAllLogs}